version: '3'

services:
  my-app:
    networks:
      - mongo_network
    image: my-app:1.0
    container_name: my-app
    ports:
      - 3000:3000
    restart: always

  mongodb:
    networks:
      - mongo_network    
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db
    restart: always

  mongo-express:
    networks:
      - mongo_network
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: always

volumes:
  mongo-db:
    driver: local

networks:
  mongo_network:
    name: mongo-network
    external: true
